### ISSUE TITLE
Change color of result

### ISSUE THREAD

**Issue by Tiv0w** [svenstaro/rofi-calc#68]
Hi!
First a big thanks for rofi-calc, I use it all the time!

I'm using [`pywal`](https://github.com/dylanaraps/pywal) to automate theming of my machine, but I encounter a serious problem with `rofi-calc`: the *result part* is always black.

This is an issue since most of my color schemes are somewhat dark, or at least my `rofi` theme is dark, so I can't really see the result.

*result very hard to see in the screenshot* 
![rofi-screenshot](https://user-images.githubusercontent.com/41124670/114703843-24ffe400-9d26-11eb-9506-ceb108832563.png)

---

I tried to tweak multiple colors in my rofi theme, no luck.
I took a look in the source of `rofi-calc`, but I can't find where the color of the output is controlled, nor the css id of the result...

So my question is: **is there anything related to the color configuration in `rofi-calc`? If not, how can I access the result from `rofi`?**

**Comment by svenstaro** [comment]
Hm weird. I don't really have time to investigate right now but feel free to poke the code a bit. I don't really do much magic on top of rofi in terms of styling so things that work for rofi should in theory also work for rofi-calc.

**Comment by mangkoran** [comment]
Uhh I think my config might answer @Tiv0w question. Here is my config of `rofi`: [config](https://github.com/mangkoran/dotfiles/tree/71bb6dec491b618837da12a02cb48e8966bca2a9/.config/rofi)

I have messing around with `rofi` config, but I still cannot find how to style the "Result" row specifically (I use global selector for the color)

**Comment by SafwanLjd** [comment]
You just need to set a default `text-color` in the global part of your theme file, so something like:

```css
* {
    text-color: #ffffff;
}
```

**Comment by orbatschow** [comment]
I experimented a little bit and found out, that the rofi-calc is using the message element. Sample config:

```css
configuration {

  calc {
    display-name: "";
  }

}

* {
    background:       #343944;
    text:             #dddddd;
    selected:         #e25252;

    background-color: rgba ( 0, 0, 0, 0 % );
    font:             "JetBrainsMono Nerd Font Medium 18";
    text-color:       var(text);
}
window {
    background-color: var(background);
    width:            120ch;
    border-radius:    5px;
}

listview {
    lines: 0;
}

inputbar {
    padding:    3ch 3ch 3ch 3ch;
    children:   [ prompt, entry ];
}

entry {
    placeholder-color: var(text);
    text-color:        var(text);
    placeholder:       "";
    cursor:            text;
}

message {
  border: 2px 0 0 0;
  border-color: var(selected);
  padding: 1.5ch 3ch 1.5ch 3ch;
  vertical-align: 0.5;
}

```
